// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4GuNq_uKmNNVG_eO5O9U6I4K364M1I_k',
    appId: '1:336443953094:web:228a9b570d630b4c22ecc7',
    messagingSenderId: '336443953094',
    projectId: 'social-f94ce',
    authDomain: 'social-f94ce.firebaseapp.com',
    storageBucket: 'social-f94ce.firebasestorage.app',
    measurementId: 'G-743DX3J4P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm6pT6-mGTaJuA21cuYYLKfRdzqv_27S0',
    appId: '1:336443953094:android:f5997d8ad9d0ef2922ecc7',
    messagingSenderId: '336443953094',
    projectId: 'social-f94ce',
    storageBucket: 'social-f94ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAntCujSm-JVF8HkTTHXQfEoQ2BueLH7WQ',
    appId: '1:336443953094:ios:8a8848272f49d18522ecc7',
    messagingSenderId: '336443953094',
    projectId: 'social-f94ce',
    storageBucket: 'social-f94ce.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAntCujSm-JVF8HkTTHXQfEoQ2BueLH7WQ',
    appId: '1:336443953094:ios:8a8848272f49d18522ecc7',
    messagingSenderId: '336443953094',
    projectId: 'social-f94ce',
    storageBucket: 'social-f94ce.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4GuNq_uKmNNVG_eO5O9U6I4K364M1I_k',
    appId: '1:336443953094:web:9aa577f2ce00190022ecc7',
    messagingSenderId: '336443953094',
    projectId: 'social-f94ce',
    authDomain: 'social-f94ce.firebaseapp.com',
    storageBucket: 'social-f94ce.firebasestorage.app',
    measurementId: 'G-2757DPKZCM',
  );

}